- name: S3 Buket List
  hosts: localhost
  tasks:
    - amazon.aws.s3_bucket_info:
      register: result

    - name: List buckets
      ansible.builtin.debug:
        msg: "{{ result['buckets'] }}"
