- name: List S3 buckets using AWS CLI
  hosts: 10.88.88.103
  gather_facts: no
  become: yes
  vars:
    AccessKey: "{{ survey_AccessKey }}"
    SecretKey: "{{ survey_SecretKey }}"
    Region: "{{ survey_Region }}"
  tasks:
    - name: Set AWS CLI environment variables
      ansible.builtin.shell: |
        export AWS_ACCESS_KEY_ID="{{ AccessKey }}"
        export AWS_SECRET_ACCESS_KEY="{{ SecretKey }}"
        export AWS_DEFAULT_REGION="{{ Region }}"
        aws s3 ls
      register: s3_bucket_list
      changed_when: no

    - name: Display S3 bucket list
      ansible.builtin.debug:
        var: s3_bucket_list.stdout