- name: List VPC AWS CLI
  hosts: 10.88.88.103
  gather_facts: yes
  vars:
    AccessKey: "{{ survey_AccessKey }}"
    SecretKey: "{{ survey_SecretKey }}"
    Region: "{{ survey_Region }}"
  tasks:
    - name: Set AWS CLI environment variables
      ansible.builtin.shell: |
        export AWS_ACCESS_KEY_ID="{{ AccessKey }}"
        export AWS_SECRET_ACCESS_KEY="{{ SecretKey }}"
        export AWS_DEFAULT_REGION="{{ Region }}"
        /snap/bin/aws ec2 describe-vpcs --query "Vpcs[]" --output json
      register: vpc_list
      changed_when: no

    - name: Display VPC list
      ansible.builtin.debug:
        var: vpc_list.stdout