- name: List S3 buckets using AWS CLI
  hosts: 10.88.88.103
  become: yes
  tasks:
    - name: Set AWS CLI environment variables
      ansible.builtin.shell: |
        export AWS_ACCESS_KEY_ID="{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        export AWS_SECRET_ACCESS_KEY="{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        export AWS_DEFAULT_REGION="ap-northeast-2"
        aws s3 ls
      register: s3_bucket_list
      changed_when: no

    - name: Display S3 bucket list
      ansible.builtin.debug:
        var: s3_bucket_list.stdout
