---
- name: List installed collections
  hosts: localhost
  tasks:
    - name: Find collections
      ansible.builtin.command: find ~/.ansible/collections/ansible_collections -type d -maxdepth 2
      register: collections

    - name: Show collections
      debug:
        msg: "{{ collections.stdout_lines }}"
