---
- name: Get-Timezone
  hosts: all
  gather_facts: false
  tasks:
    - name: Get-Timezone
      ansible.builtin.powershell:
        script: |
          Get-Timezone
      register: timezone
    - name: Print timezone output
      debug:
        msg: "{{ timezone.stdout }}"
