---
- name: Get AD Password Policy
  hosts: all
  gather_facts: no
  tasks:
    - name: Get AD Password Policy
      ansible.builtin.win_shell: Get-ADDefaultDomainPasswordPolicy
      register: ad_password_policy_output

    - name: Show AD Password Policy
      ansible.builtin.debug:
        msg: "{{ ad_password_policy_output.stdout_lines }}"
        verbosity: 0
