---
- name: Get-Timezone using win_shell
  hosts: all
  gather_facts: false
  tasks:
    - name: Get-Timezone
      win_shell: Get-Timezone
      register: timezone
    - name: Print timezone output
      debug:
        msg: "{{ timezone.stdout }}"
