---
- name: Install Visual Studio Code
  hosts: all
  tasks:
    - name: Check if Visual Studio Code is already installed
      win_shell: |
        if (Test-Path "C:\Program Files\Microsoft VS Code\Code.exe") {
          Write-Output "installed"
        } else {
          Write-Output "not installed"
        }
      register: vscode_status
      changed_when: no

    - name: Set status based on output
      set_fact:
        is_vscode_installed: "{{ vscode_status.stdout | trim == 'installed' }}"

    - name: Debug installation status
      debug:
        msg: "VS Code installation status: {{ 'Installed' if is_vscode_installed else 'Not Installed' }}"

    - name: Download VS Code installer
      win_get_url:
        url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
        dest: "C:\\Temp\\VSCodeSetup.exe"
      when: not is_vscode_installed

    - name: Install VS Code
      win_shell: |
        Start-Process -FilePath "C:\Temp\VSCodeSetup.exe" -ArgumentList "/silent /mergetasks=!runcode" -Wait
      args:
        executable: powershell
      when: not is_vscode_installed

    - name: Remove installer after installation
      win_file:
        path: "C:\\Temp\\VSCodeSetup.exe"
        state: absent
      when: not is_vscode_installed
