---
- name: Uninstall Notepad++ silently
  hosts: all
  tasks:
    - name: Check if Notepad++ uninstall file exists
      win_shell: |
        if (Test-Path "C:\Program Files\Notepad++\uninstall.exe") {
          Write-Output "uninstall available"
        } else {
          Write-Output "uninstall not available"
        }
      register: uninstall_status
      changed_when: no

    - name: Debug uninstall file status
      debug:
        msg: "Uninstall file status: {{ uninstall_status.stdout | trim }}"

    - name: Run Notepad++ uninstaller in silent mode
      win_shell: |
        Start-Process -FilePath "C:\Program Files\Notepad++\uninstall.exe" -ArgumentList "/S" -Wait
      args:
        executable: powershell
      when: uninstall_status.stdout | trim == "uninstall available"

    - name: Remove leftover Notepad++ files
      win_file:
        path: "C:\\Program Files\\Notepad++"
        state: absent
      when: uninstall_status.stdout | trim == "uninstall available"
